-- Find total customers by countries 
SELECT 
country,
COUNT(customer_id) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find total customers by gender
SELECT 
gender,
COUNT(customer_id) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Find total products by category
SELECT 
category,
COUNT(product_id) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER total_products DESC;

-- What is the average costs in each category?
SELECT 
category,
AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;

-- What is the total revenue generated for each category?
SELECT 
dp.category,
SUM(fs.sales_amount) AS total_revenue
FROM gold.dim_products dp
LEFT JOIN gold.fact_sales fs
ON        dp.product_key = fs.product_key
GROUP BY dp.category
ORDER BY total_revenue DESC;

-- Find total revenue is generated by each customer
SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.dim_customers c
LEFT JOIN gold.fact_sales f
ON c.customer_key = f.customer_key
GROUP BY c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue;


-- What is the distribution of sold items across countries?
SELECT
c.country,
SUM(s.quantity) AS total_sold_items
FROM gold.dim_customers c
LEFT JOIN gold.fact_sales s
ON c.customer_key = s.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;
